# Generated by Django 4.2 on 2023-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0002_video_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='performers',
            field=models.ManyToManyField(blank=True, null=True, to='serializer.performer'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='serializer.tag'),
        ),
    ]
