# Generated by Django 4.2 on 2023-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0007_video_productimage_video_productsumple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
