# Generated by Django 4.2 on 2023-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0004_video_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maker',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='series',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
