# Generated by Django 4.2 on 2023-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0008_performer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
