# Generated by Django 4.2 on 2023-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0003_alter_video_performers_alter_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='images',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
