# Generated by Django 4.2 on 2023-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0006_video_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='productimage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='productsumple',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='productthumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
