# Generated by Django 4.2 on 2023-10-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0010_contentstag_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('classmajor', models.CharField(blank=True, max_length=255, null=True)),
                ('classmedium', models.CharField(blank=True, max_length=255, null=True)),
                ('classminor', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=255, null=True)),
                ('images', models.CharField(blank=True, max_length=1023, null=True)),
                ('affiliateurl', models.URLField(blank=True, null=True)),
                ('post_day', models.DateField()),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='affiliateurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
